# KiBot config file
kibot:
  version: 1

preflight:
  erc: true
  drc:
    enabled: true
    ignore_unconnected: false
    schematic_parity: true
    filters:
      - filter: 'Ignore J1 (USB receptacle) NPTH pad too close to pads'
        error: 'hole_clearance'
        regex: 'NPTH pad of J1'
  check_zone_fills: true
  update_xml: false

outputs:
  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: 'docs'
    options:
      output: Schematic.pdf

  - name: 'print_PCB_top'
    comment: "Print top PCB side"
    type: pcbdraw
    dir: 'docs'
    options:
      # [boolean=false] render the bottom side of the board (default is top side)
      bottom: false
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      dnf_filter: ''
      # [number=300] [10,1200] dots per inch (resolution) of the generated image
      dpi: 1200
      # [string='svg'] [svg,png,jpg] output format. Only used if no `output` is specified
      format: 'png'
      # [list(string)=[]] list of components to highlight
      highlight: []
      # [boolean=false] mirror the board
      mirror: false
      # [boolean=false] do not make holes transparent
      no_drillholes: false
      # [string='%f-%i%v.%x'] name for the generated file. Affected by global options
      output: '%f-%i.%x'
      # [boolean=false] show placeholder for missing components
      placeholder: false
      # [list(string)|string=none] [none,all] list of components to draw, can be also a string for none or all.
      show_components: none

  - name: 'print_PCB_bottom'
    comment: "Print bottom PCB side"
    type: pcbdraw
    dir: 'docs'
    options:
      # [boolean=false] render the bottom side of the board (default is top side)
      bottom: true
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      dnf_filter: ''
      # [number=300] [10,1200] dots per inch (resolution) of the generated image
      dpi: 1200
      # [string='svg'] [svg,png,jpg] output format. Only used if no `output` is specified
      format: 'png'
      # [list(string)=[]] list of components to highlight
      highlight: []
      # [boolean=false] mirror the board
      mirror: true
      # [boolean=false] do not make holes transparent
      no_drillholes: false
      # [string='%f-%i%v.%x'] name for the generated file. Affected by global options
      output: '%f-%i.%x'
      # [boolean=false] show placeholder for missing components
      placeholder: false
      # [list(string)|string=none] [none,all] list of components to draw, can be also a string for none or all.
      # The default is none
      show_components: none

  - name: '3D_top_view'
    comment: '3D render'
    type: blender_export
    dir: 'docs'
    options:
      pcb3d:
        show_components: all
      render_options:
        transparent_background: true
        samples: 20
      point_of_view:
        rotate_x: 30
        rotate_z: -20
      outputs:
        - type: render
